### PR TITLE
Update to dropwizard 4.0.x beta

### PR DESCRIPTION
**Pull request by cml37**
These changes capture the general idea of updating to be dropwizard 4.0.x beta compliant.  Unit test could probably be beefed up a little with the right mocks (I removed tests that were failing due to the new design).

### CODE REVIEW

**Comment by TomCools** [comment]
HI, thanks for this.

I honestly haven't looked into this project that much anymore... and I'm unsure how I will continue. 
Do you really intend to use this module with Dropwizard? If so, I might look into it, else, I'm thinking about just not moving it to 4.X.

Kind regards,
Tom

**Comment by cml37** [comment]
You bet!  I'm actually using it, if you merge this commit, you should be good to go!  I've been running with these changes for a few weeks at this point

**Comment by TomCools** [comment]
I’ll have a look at it this weekend 😊.
Might be changing the name of the bundle/jar a little, since it’s no longer jee7 now.

I’ll keep you up to date!

Met vriendelijke groet,
Kind regards,

Tom Cools

**Comment by TomCools** [comment]
Hi!

I haven't worked on this project in quite a bit, even the Travis CI pipeline is fully broken... but since you've expressed interest in the project, I'm willing to reboot it for Dropwizard 4. I'll be merging this merge request, then do some serious maintenance and setting up build pipelines again. 

Will likely be renaming it to dropwizard-websocket-jsr356, as Java EE 7 has been a while now. Keep an eye on the repo.

Thanks for your contribution!

**Comment by cml37** [comment]
Wonderful!! This is great to hear.  I'll be on the lookout.  Thanks much!

**Comment by TomCools** [comment]
@cml37 Beta release just went live. Changed the name of the bundle to be more accurate ;).

```
<dependency>
  <groupId>be.tomcools</groupId>
  <artifactId>dropwizard-websocket-jsr356-bundle</artifactId>
  <version>4.0.0-beta.1</version>
</dependency>
```

Should be going through Maven Central as we speak. Thanks for the contribution! I'll be setting up a decent contribution pipeline in the near future.

**Comment by cml37** [comment]
Wonderful!  I just imported it.  Thanks again!!

**Pull request merged**
