### PR TITLE
Upgrade dropwizard to 1.0.0 and Jetty accordingly

### PR DESCRIPTION
**Pull request by hlangli**

### CODE REVIEW

**Comment by TomCools** [comment]
Hi, I quickly checked and the Travic CI build is failing for oraclejdk7. I'm going to investigate first why this is happening before I merge. 

I find it weird that it is failing, because I can't really any changes you made that should break this.

**Comment by TomCools** [comment]
Never mind, i just figured out that Dropwizard 1.0.0 does no longer support Java 7 and below. I will do the merge this weekend when I have time.

**Comment by jms-calado** [comment]
@TomCools It's been more than a year since the last update. Any chance for an update?

**Comment by TomCools** [comment]
@jms-calado Yes, i watch this like a hawk. I will be creating a 2.0.0 version of this bundle, and merge this in. Major version number because Java 7 is no longer supported.
I do have to setup the maven central deployment again, but i will look at that this weekend.
Expect a release before the end of the month. (At the latest!, hopefully it is done tomorrow evening)

Kind regards;
Tom

**Pull request merged**
